# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sughrahammad
# "service" is the name of this project. This will also be added to your AWS resource names.
service: shui-backend

provider:
    name: aws
    runtime: nodejs24.x
    architecture: arm64
    region: eu-north-1
    httpApi:
      cors: true

    iam:
      role: ${file(./config.yml):role}
    environment:
      TABLE_NAME: !Ref shuiTable
      JWT_SECRET: ${file(./config.yml):jwtSecret}


functions:
  ##auth
  register:
    handler: functions/auth/register/index.handler
    events:
      - httpApi:
          path: /api/auth/register
          method: POST
  login:
    handler: functions/auth/login/index.handler
    events:
      - httpApi:
          path: /api/auth/login
          method: POST
  ##messages
  createMessage:
    handler: functions/messages/createMessage/index.handler
    events:
      - httpApi:
          path: /api/messages
          method: POST
  getAllMessages:
    handler: functions/messages/getAllMessages/index.handler
    events:
      - httpApi:
          path: /api/messages
          method: GET

  getMessageById:
    handler: functions/messages/getMessageById/index.handler
    events:
      - httpApi:
          path: /api/messages/{id}
          method: GET
  
  updateMessage:
    handler: functions/messages/updateMessage/index.handler
    events:
      - httpApi:
          path: /api/messages/{id}
          method: PATCH

  deleteMessage:
    handler: functions/messages/deleteMessage/index.handler
    events:
      - httpApi:
          path: /api/messages/{id}
          method: DELETE

   
resources:
  Resources:
    shuiTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shuiTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
          - AttributeName: GSI2PK
            AttributeType: S
          - AttributeName: GSI2SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: GSI2
            KeySchema:
              - AttributeName: GSI2PK
                KeyType: HASH
              - AttributeName: GSI2SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
